language: csharp
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - dotnet build ./Wobble
  - dotnet test ./Wobble.Tests.Unit/Wobble.Tests.Unit.csproj
after_success:
 - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh success $WEBHOOK_URL
after_failure:
 - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh failure $WEBHOOK_URL
