language: csharp
solution: Wobble.sln
mono: none
dotnet: 2.0.0
install:
- dotnet restore
script:
 - dotnet build
 - dotnet test MTAServiceStatus.Tests/MTAServiceStatus.Tests.csproj
 after_success:
  - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
